version: '3.8'

services:
  node:
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    volumes:
      - ./:/usr/app
      - /usr/app/log
    command: /usr/app/node_modules/.bin/nodemon -L src/server.ts

    networks:
      - user-networks

  postgres:
    build: ./database
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always

networks:
  user-networks:
    driver: bridge

volumes:
  pg-data:
